// Generated by gencpp from file sentinel_drone/Geolocation.msg
// DO NOT EDIT!


#ifndef SENTINEL_DRONE_MESSAGE_GEOLOCATION_H
#define SENTINEL_DRONE_MESSAGE_GEOLOCATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sentinel_drone
{
template <class ContainerAllocator>
struct Geolocation_
{
  typedef Geolocation_<ContainerAllocator> Type;

  Geolocation_()
    : objectid()
    , lat(0.0)
    , long(0.0)  {
    }
  Geolocation_(const ContainerAllocator& _alloc)
    : objectid(_alloc)
    , lat(0.0)
    , long(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _objectid_type;
  _objectid_type objectid;

   typedef float _lat_type;
  _lat_type lat;

   typedef float _long_type;
  _long_type long;





  typedef boost::shared_ptr< ::sentinel_drone::Geolocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentinel_drone::Geolocation_<ContainerAllocator> const> ConstPtr;

}; // struct Geolocation_

typedef ::sentinel_drone::Geolocation_<std::allocator<void> > Geolocation;

typedef boost::shared_ptr< ::sentinel_drone::Geolocation > GeolocationPtr;
typedef boost::shared_ptr< ::sentinel_drone::Geolocation const> GeolocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentinel_drone::Geolocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentinel_drone::Geolocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sentinel_drone::Geolocation_<ContainerAllocator1> & lhs, const ::sentinel_drone::Geolocation_<ContainerAllocator2> & rhs)
{
  return lhs.objectid == rhs.objectid &&
    lhs.lat == rhs.lat &&
    lhs.long == rhs.long;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sentinel_drone::Geolocation_<ContainerAllocator1> & lhs, const ::sentinel_drone::Geolocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sentinel_drone

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone::Geolocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone::Geolocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone::Geolocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone::Geolocation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone::Geolocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone::Geolocation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentinel_drone::Geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e34099979df01fb50f0f5a329758ba04";
  }

  static const char* value(const ::sentinel_drone::Geolocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe34099979df01fb5ULL;
  static const uint64_t static_value2 = 0x0f0f5a329758ba04ULL;
};

template<class ContainerAllocator>
struct DataType< ::sentinel_drone::Geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentinel_drone/Geolocation";
  }

  static const char* value(const ::sentinel_drone::Geolocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentinel_drone::Geolocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string objectid\n"
"float32 lat\n"
"float32 long\n"
;
  }

  static const char* value(const ::sentinel_drone::Geolocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentinel_drone::Geolocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objectid);
      stream.next(m.lat);
      stream.next(m.long);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Geolocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentinel_drone::Geolocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentinel_drone::Geolocation_<ContainerAllocator>& v)
  {
    s << indent << "objectid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.objectid);
    s << indent << "lat: ";
    Printer<float>::stream(s, indent + "  ", v.lat);
    s << indent << "long: ";
    Printer<float>::stream(s, indent + "  ", v.long);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTINEL_DRONE_MESSAGE_GEOLOCATION_H
